### ISSUE TITLE
No support for LaTex

### ISSUE THREAD

**Issue by kurtispykes** [dexplo/jupyter_to_medium#16]
When deployed to Medium, LaTex text is not parsed as an image. 

Result given when deployed to Medium
<img width="463" alt="latex" src="https://user-images.githubusercontent.com/43003716/88811301-4a57bc80-d1ae-11ea-9bf7-6dfdbe1df891.png">

**Comment by tdpetrou** [comment]
Thanks for adding this. Will add to the roadmap and get to it at a later time.

**Comment by rparraca** [comment]
Thank you @kurtispykes for adding this... I was going to add the same issue.

@tdpetrou I'd be happy to take a look at it and help if help is needed/welcomed =)

**Comment by mjam03** [comment]
I had a go yesterday at doing this and it turns out it's:
 - Nothing really to do with jupyter_to_medium - it's more a fundamental challenge with latex embedded in markdown
 - It's harder than it sounds

I tried various solutions like [this one](https://stackoverflow.com/questions/9818279/render-equation-to-png-file-using-python) - identify latex then use matplotlib to .png it then embed as image but this will only really work for a cell completely occupied by latex.

It's not going to work for cells where I talk about '$x$' or '$y$' and want the latex to be embedded with the text. I haven't yet found a solution that beats unfortunately using the medium editor and screenshot-ing the rendered latex from a notebook. Even this method prevents the ability to mix latex and text in a single markdown cell.

Have you seen anywhere else in the last 6 months that handles this well or can point me to any stuff? Would be happy to do some more research and try to implement.

**Comment by martinlarsalbert** [comment]
Building on the idea from @mjam03 I used Matplotlib to render the LaTeX so that it will be saved as inline figures in the notebook, and will consequently be send to Medium. Here is an [example](https://github.com/martinlarsalbert/kaggle/blob/main/kernels/y-is-normal/y-is-normal.ipynb).

This means that you will need to modify your notebook to get this to work, which is not ideal, but still easier to do manual work in generating the equations as images. 

I don't know if there is some elegant way to automate something like this in the present package (which I find great by the way! :)

**Comment by mjam03** [comment]
I've had another look at this one and think I can manage it. The idea will be modest at first and will only work for cells which are pure Latex i.e. not '$x$' embedded in amongst other text but a cell which contains only '$$mathjax_latex_code$$'. Will see if I can sort it tomorrow but will be doing the following:
 - create another preprocessor to handle this
 - preprocessor will check input to see if it starts with '$$' and finishes with '$$' denoting it a 'latex cell'
 - this should work even for multi-line expressions although from first glance things like `\begin{align}` don't seem to work with the matplotlib conversion (which is annoying for aligned multi-line equations)
 - use the matplotlib conversion to strip the latex out, convert to an image and insert this image back into the notebook in place of the latex code cell
 - the image preprocessor will then do the work of inserting this image into our Medium article through the previous process

I'll give it a go and see how it turns out - if it works well then it's a nice way to avoid having to amend the notebook to have inline figure as @martinlarsalbert has suggested. If not then I'll explore if we can merge that idea in as having support for latex would be really nice.

**Comment by mjam03** [comment]
I think I've managed it. It's limited in scope but it seems to work pretty well. The following is what I did (I'll write some documentation for it and do a proper release to PyPI this week):
 - go through the notebook and look for cells where the source starts with and finishes with '$$' - this is what denotes a LaTeX code block without any text as trying top convert LaTeX surrounded  by normal text is very challenging
 - once we have those cells, then alter their format by:
   - removing the '$$' signs
   - removing things like `\begin{align}` and `\end{align}` as the matplotlib latex converter doesn't support these
   - try to replace the above alignment tags 'cleverly' so the equation _should_ still look pretty aligned
   - run the converted LaTeX string through the matplotlib converter to generate an image
   - embed this image in the notebook where the markdown LaTeX code was
 - then the standard process of finding the images and uploading them to the medium server takes over
