### ISSUE TITLE
Code block with syntax highlighting 

### ISSUE THREAD

**Issue by thigm85** [dexplo/jupyter_to_medium#22]
This is more on the lines of feature request/question than a real issue. Have you considered adding syntax highlighting similar to what [fastpages](https://fastpages.fast.ai/) offers when converting notebooks to blog posts? For example, the following medium-style code block

![Skjermbilde 2020-10-28 kl  13 20 07](https://user-images.githubusercontent.com/2162939/97435207-6808ff00-1920-11eb-8575-b0be2c54968e.png)

would become

![Skjermbilde 2020-10-28 kl  13 20 18](https://user-images.githubusercontent.com/2162939/97435223-6fc8a380-1920-11eb-852a-737d6243a4e1.png)

**Comment by lc5415** [comment]
I think this is a problem to do with Medium more than this package. The best solution would for Medium to support Markdown-style syntax highlighting like GitHub or Stackoverflow do, or most websites that support Markdown.

Another workaround would be for this package to upload every code block as a gist

**Comment by thigm85** [comment]
I agree this is not a problem with this package. But this package solved many Medium limitations with useful workarounds. For example, tables are hard to create in Medium, and this was solved by taking pictures of the tables instead. I just wonder if similar solutions would be possible for code blocks. For example, using a picture as I did above to upload the code block to Medium.

**Comment by mjam03** [comment]
Hi, not sure this is exactly what you're after but I've raised this [here](https://github.com/dexplo/jupyter_to_medium/issues/28) and also the PR to add it. The idea is that for any code blocks, jtm will:
 - Identify them over a certain threshold you specify (e.g. 5 lines)
 - Any code block greater than that it will create on-the-fly a gist for you
 - Insert that embedded ref into the .md instead of the un-formatted standard grey markdown (`like this`)
 - Publish that modified markdown to medium where the embedded gists show in Medium with formatting

It's not perfect (gist doesn't let you choose theme etc) but helps instead of having large unformatted chunks of grey in your posts.

**Comment by thigm85** [comment]
Yeah, gistfy the code blocks would be great to have.

**Comment by mjam03** [comment]
Going to close this as I have added support to 'gistify' code snippets with a parameter to only do this for code blocks that exceed `x` lines. Let me know if you have any problems or suggested modifications/improvements.

**Comment by thigm85** [comment]
Cool, thanks. I will give it a try next time I use it.
