### ISSUE TITLE
Error when exporting Latex formulas

### ISSUE THREAD

**Issue by edoglione** [dexplo/jupyter_to_medium#59]
When exporting in Medium, the Latex formulas are rendered as code as per attached example

![immagine](https://user-images.githubusercontent.com/64694875/186921914-fbef4b28-98a3-49ab-b3b2-7d050fe34727.png)

**Comment by mjam03** [comment]
Hi there,

Sorry for the delay in getting back to you. For the moment, only latex that is centred is supported - this is because we need to identify the full cell to convert to latex as we convert and then screenshot it to be an image.

In your example, if you'd like to insert that snippet as latex then you can write in a call:

`$$p_i = p_0(1-\lambda)$$`

I've just checked and this still works as expected - producing a centred image of your formula. I'm going to close this for now, but if this is something that you really need then it would be great if you could help by contributing it. Unfortunately in order to support in line latex (in line with your text) that would require medium to support those kinds of special mathematicaly characters.

Mark
